---
language: python
cache:
  - pip
  - directories:
      - "node_modules"
      - $HOME/.cache
os:
  - linux
stages:
  - lint
  - docs
  - test
  - deploy
install:
  - pip install -q tox-travis tox-pyenv virtualenv wheel | cat
  - which tox >/dev/null || if [ -z ${VIRTUAL_ENV+x} ]; then python -m pip install --user tox tox-pyenv ; else python -m pip install tox tox-pyenv twine; fi
notifications:
  email:
    - pycontribs@googlegroups.com
jobs:
  include:
    - stage: lint
      script:
        # package building added here purely to fail-fast if is broken
        - python setup.py sdist bdist_wheel
        - python -m tox
      env: TOXENV=lint
      python: "2.7"
    - stage: docs
      script: python -m tox
      python: "2.7"
      env: TOXENV=docs
    - stage: test
      script: python -m tox
      python: "2.7"
      env: TOXENV=py27
      after_success:
        - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
    - stage: test
      script: python -m tox
      python: "3.4"
      env: TOXENV=py34
      after_success:
        - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
    - stage: test
      script: python -m tox
      python: "3.5"
      env: TOXENV=py35
      after_success:
        - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
    - stage: test
      script: python -m tox
      python: "3.6"
      env: TOXENV=py36 PYTHON='3.6' PYENV_VERSION='system'
      after_success:
        - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
    - stage: test
      script: python -m pip install -q tox-travis && python -m tox
      python: "3.7"
      env: TOXENV=py37 PYTHON='3.7'
      after_success:
        - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
      # begin: workaround to enable support for py37: https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      sudo: required
      # end
    - stage: deploy
      script:
        - python setup.py sdist bdist_wheel
        - python -m twine upload dist/*
      if: tag IS present
      deploy:
        - provider: releases
          api_key:
            secure: Dz7yMcIBxTKD2zYi0ph9qTz2N0AdmOWD9eI/CMW3DdXh15e4fQqL7O5cr4Sn+FSKHMbUCUoztXwJsYLbrCPB2tH8HliPhSuNzb0CwScRD9wSzQzhli10YPj+Oe2UlPOcIWQFRYTUQ1tfpvfDcvRL7klLDiKUpghJ+xf7crXzqGE=
          file_glob: true
          file:
            - dist/*
            - ChangeLog
          skip_cleanup: true
          on:
            tags: true
            repo: pycontribs/tendo
            branch: master
env:
  global:
    - secure: "pGQGM5YmHvOgaKihOyzb3k6bdqLQnZQ2OXO9QrfXlXwtop3zvZQi80Q+01l230x2psDWlwvqWTknAjAt1w463fYXPwpoSvKVCsLSSbjrf2l56nrDqnoir+n0CBy288+eIdaGEfzcxDiuULeKjlg08zrqjcjLjW0bDbBrlTXsb5U="
    - PIP_DISABLE_PIP_VERSION_CHECK=1
    - TRAVIS_NODE_VERSION="v8.11.3"
